"""Require exchange.amount_eur

Revision ID: 30b2f2a1efd4
Revises: 5911cf614d11
Create Date: 2025-03-12 18:15:41.808052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '30b2f2a1efd4'
down_revision: Union[str, None] = '5911cf614d11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exchange', 'amount_eur',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exchange', 'amount_eur',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
