"""Added actual_misc_account

Revision ID: 41b460cf52e3
Revises: 30b2f2a1efd4
Create Date: 2025-03-12 23:58:18.088631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '41b460cf52e3'
down_revision: Union[str, None] = '30b2f2a1efd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('actual_misc_account', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'actual_misc_account')
    # ### end Alembic commands ###
