"""Added ondelete

Revision ID: 5911cf614d11
Revises: 14eecbaf6ca8
Create Date: 2025-03-11 09:25:25.630892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5911cf614d11'
down_revision: Union[str, None] = '14eecbaf6ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('account_bank_account_id_fkey', 'account', type_='foreignkey')
    op.drop_constraint('account_plaid_account_id_fkey', 'account', type_='foreignkey')
    op.create_foreign_key(None, 'account', 'plaidaccount', ['plaid_account_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'account', 'bankaccount', ['bank_account_id'], ['id'], ondelete='SET NULL')
    op.add_column('bankaccount', sa.Column('plaid_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bankaccount', 'plaidaccount', ['plaid_account_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bankaccount', type_='foreignkey')
    op.drop_column('bankaccount', 'plaid_account_id')
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.create_foreign_key('account_plaid_account_id_fkey', 'account', 'plaidaccount', ['plaid_account_id'], ['id'])
    op.create_foreign_key('account_bank_account_id_fkey', 'account', 'bankaccount', ['bank_account_id'], ['id'])
    # ### end Alembic commands ###
