"""Added cursor column

Revision ID: 73684eb0c72b
Revises: 41b460cf52e3
Create Date: 2025-03-16 14:37:50.232168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '73684eb0c72b'
down_revision: Union[str, None] = '41b460cf52e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plaidaccount', sa.Column('cursor', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plaidaccount', 'cursor')
    # ### end Alembic commands ###
