name: Build and Push Scripts

on:
  push:
    branches:
      - main
    paths:
      - scripts/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push scripts
        uses: docker/build-push-action@v6
        with:
          context: scripts
          push: true
          tags: ghcr.io/antoncuranz/money-tracking/scripts:latest
